version: 0.2

phases:
  build:
    commands:
      - echo "Building upload-to-search"
      - cd upload-to-search
      - zip -r function.zip .

artifacts:
  files:
    - upload-to-search/function.zip