version: 0.2

phases:
  build:
    commands:
      - echo "Building searchFunction"
      - cd searchFunction
      - zip -r function.zip .

artifacts:
  files:
    - searchFunction/function.zip
    - searchFunction/search-function.yaml
